services:
  - type: web
    name: business-plan-backend
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://business-plan-backend.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: business-plan-db
          property: connectionString.Host
      - key: DB_PORT
        fromDatabase:
          name: business-plan-db
          property: connectionString.Port
      - key: DB_DATABASE
        fromDatabase:
          name: business-plan-db
          property: connectionString.Database
      - key: DB_USERNAME
        fromDatabase:
          name: business-plan-db
          property: connectionString.Username
      - key: DB_PASSWORD
        fromDatabase:
          name: business-plan-db
          property: connectionString.Password

databases:
  - name: business-plan-db
    plan: free
    # La configuration de la base de données se fait via l'interface de Render
    # Les propriétés engine et version sont gérées automatiquement

# Note: Pour la configuration de la base de données en développement local,
# utilisez un fichier .env séparé qui n'est pas versionné.
