services:
  - type: web
    name: business-plan-backend
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan migrate --force
      php artisan storage:link
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${MYSQLHOST}
      - key: DB_PORT
        value: ${MYSQLPORT}
      - key: DB_DATABASE
        value: ${MYSQLDATABASE}
      - key: DB_USERNAME
        value: ${MYSQLUSER}
      - key: DB_PASSWORD
        value: ${MYSQLPASSWORD}
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/mysql/certs/ca-certificate.crt
