services:
  - type: web
    name: business-plan-backend
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: "php artisan migrate --force && php artisan db:seed --force"

    envVars:
      - key: APP_KEY
        value: base64:VMhFpdmFjWDEI5pLJhNJPKfk134hb2O8K6qLffSlPFo=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://business-plan-backend.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: business-plan-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: business-plan-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: business-plan-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: business-plan-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: business-plan-db
          property: password

databases:
  - name: business-plan-db
    plan: free
